### PR TITLE
Change to use agnostic functions for isochrones and geocode-street an…

### LINKED ISSUE #164: Remove provider info and use generic functions for LDS
- [x] Changes in camshaft to not decide any default provider and delegate that into dataservices-api, which will do based on config (camshaft will only use the "generic functions" with no reference to the provider)

### PR DESCRIPTION
**Pull request by ethervoid**
Closes #164 

- Remove the provider parameter for geocode-street-address and trade-area analyses
- Start using provider agnostic functions from dataservices API client

### CODE REVIEW

**Comment by ethervoid** [comment]
restest this please

**Comment by ethervoid** [comment]
retest this please

**Comment by ethervoid** [comment]
Please @dgaubert could you CR this?

// @rafatower

**Comment by rafatower** [comment]
What surprises me is that there's no isodistance here (I searched the code and couldn't find it). Ok.

**Comment by ethervoid** [comment]
Nope, I think the isodistance part is made with ST_Buffer instead of use cdb_isodistance function

**Comment by dgaubert** [comment]
Since provider functions no longer exist, please remove its mocks in [fixtures](https://github.com/CartoDB/camshaft/tree/8f7aad4faa52759adb534b8aee5637bdc5ec7a80/test/fixtures/cdb_dataservices_client).

**Comment by dgaubert** [comment]
👍

**Comment by rochoa** [comment]
@rafatower Do you think it would be better to use isodistance instead of our custom st_buffer usage?

**Comment by rafatower** [comment]
Indeed, I think so.

**Comment by rafatower** [comment]
Pros: closer to user expectations (actual area of influence?). Cons: slower and potentially "pricey". I guess its mostly a product decision and can wait for having more stable isodistance providers.

**Comment by rochoa** [comment]
Then maybe I misunderstood the problem. I thought we were talking about `buffer` analysis.

**Comment by rafatower** [comment]
Probably my confusion, sorry. Then they are two different analyses: `buffer` (already implemented) and `isodistance` (to be implemented, I guess). Just ignore this thread, wrong place and timing for it.

**Comment by rochoa** [comment]
Don't worry, I guess I also misguided you 😈 .

**Pull request merged**
