### PR TITLE
Add Node v6 LTS support

### LINKED ISSUE #247: [node-v6] Node v6 LTS support
Support for Node 0.10.x has ended in October 2016. We need to migrate to the latest Node LTS version (v6.9.1)

### PR DESCRIPTION
**Pull request by dgaubert**
Fixes #247

### CODE REVIEW

**Comment by dgaubert** [comment]
We should use cartodb-psql@0.7.1 to avoid max listeners issue, shouldn't we?

**Comment by dgaubert** [comment]
:shipit: ??

**Comment by rochoa** [comment]
It's still pointing to 0.7.0, isn't it?

**Comment by dgaubert** [comment]
I've just merged it. (I skipped CR step)

https://github.com/CartoDB/camshaft/blob/master/package.json

**Comment by rochoa** [comment]
Oh, I didn't realise, I was checking the code in this PR.

Yes, :shipit: .

**Comment by dgaubert** [comment]
On it!

**Pull request merged**
