### PR TITLE
Bind node itself in beforeCreate function for better semantics

### PR DESCRIPTION
**Pull request by rochoa**
It's easier to understand what you are affecting when you work
with `this` instead with a pass by reference `node` variable.

This will align with other hooks like one for being able to execute
an arbitrary query before creating the node to ensure/validate some
metadata is present in the created node.

### CODE REVIEW

**Comment by dgaubert** [comment]
Apart from aligning with `preCheck` hook. Is your idea to move `beforeCreate` hook from options to a object method for each node's subclasses or are we going to keep both approach?

**Comment by rochoa** [comment]
Interesting question!

Could you outline how that code could be? I mean, how would you define a node with that _object method_?

**Comment by dgaubert** [comment]
Something like this: https://github.com/CartoDB/camshaft/compare/before-create-bind...before-create-as-object-method

That leads to rely more on inheritance which is something that I'm not sure If you want to avoid. 😈

**Comment by rochoa** [comment]
Yep, that's an option we have.

Actually, when I was doing the changes for this PR, for a moment I thought about doing:

```
this.beforeCreate = options.beforeCreate.bind(this);
this.beforeCreate();
```

So that would be compatible with your approach, allowing to override it in the prototype. What do you think about doing that change? It would be something like:

```diff
diff --git a/lib/node/node.js b/lib/node/node.js
index 42112be..e3a5a62 100644
--- a/lib/node/node.js
+++ b/lib/node/node.js
@@ -367,6 +367,9 @@ Node.prototype.toDot = function() {
     };
 };

+Node.prototype.beforeCreate = function() {
+};
+
 module.exports.PARAM = {
     NODE: function() {
         var args = (arguments.length === 1 ? [arguments[0]] : Array.apply(null, arguments));
@@ -449,8 +452,9 @@ module.exports.create = function createNode(type, expectedParams, options) {
         // `beforeCreate` allows to change/modify the node before it's actually created/returned
         // if it throws an error it will fail to create the node.
         if (options.beforeCreate) {
-            options.beforeCreate.bind(this)();
+            this.beforeCreate = options.beforeCreate.bind(this);
         }
+        this.beforeCreate();
         this.validators = Array.isArray(options.validators) ? options.validators : [];
     }
     util.inherits(BaseNode, Node);
```

**Comment by dgaubert** [comment]
Pretty nice! 💪 

Having a default `beforeCreate` that could be overridden by subclassing and/or by options sounds really good. 

Being a PITA, the following question is: are we going to need such mechanism in the near future? ;)

**Comment by rochoa** [comment]
I don't think so. All the existing analyses use the `Node.create` for defining the classes. So I would keep it simple. Thoughts?

**Comment by dgaubert** [comment]
Neither do I. Let's keep it simple.

More than once I had a thought if a classic design pattern could be applicable here. No sure if it's worth refactoring.

**Pull request merged**
